controllers:
    resource:
        path: '../src/Controller/'
        namespace: 'App\Controller'
    type: 'attribute'

homepage:
    path: '/'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
    defaults:
        route:           'app_movies_list'
        permanent:       false
        keepQueryParams: true
